---
- hosts: localhost 
  tasks: 
  - name: Ansible command module multiple commands 
    command: "touch {{ item }}"
    with_items: 
      - hello.txt 
      - hello2.txt 
      - hello3.txt 
    args:
      chdir: /root/ansible
